### PR TITLE
 Add new query string parameter for excludedTags

### PR DESCRIPTION
**Pull request by LockTar**
Add optional query string parameter to filter out operations that have a particular tags.
Excluded tags can be comma separated.

### CODE REVIEW

**Comment by justinyoo** [comment]
@LockTar I don't understand the purpose of the excluded tags. Do you want to exclude certain endpoints from the Swagger definition, which have a specific tag?

**Comment by LockTar** [comment]
> @LockTar I don't understand the purpose of the excluded tags. Do you want to exclude certain endpoints from the Swagger definition, which have a specific tag?

Yes, we needed the option for that. That's why it is an optional parameter. 

We needed to exclude some operations because they where for internal purpose (of course security was correct). We have automated the swagger file import into Azure APIM. This will generate all the operations and we only needed the public operations. Of course we could have created an intern and public function app but that is more work...

**Comment by justinyoo** [comment]
Is `OpenApiIgnoreAttribute` not enough? It only hides the endpoint from the Swagger definition.

**Comment by LockTar** [comment]
> Is `OpenApiIgnoreAttribute` not enough? It only hides the endpoint from the Swagger definition.

Normally yes but we needed the other operations in a different file so we used the same technique but then different values of the new parameter.

**Comment by justinyoo** [comment]
@LockTar As [v3.0.0](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/3.0.0) has been released with massive breaking changes, we should move your code onto [OpenApi.Core](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi.Core/3.0.0). Would you please have a look?

**Comment by LockTar** [comment]
Well, normally I don't mind but this PR is more than 1 year old so I'm not really into the code anymore. I'm also not on that project anymore so sorry I will skip this one. Hopefully you can simply port it to v3.

**Comment by justinyoo** [comment]
Thanks!

**Pull request closed without merging**
