### PR TITLE
Add GetOpenApiSecurityRequirements

### PR DESCRIPTION
**Pull request by gsteencg**
Allow the end user to customize the security requirements

### CODE REVIEW

**Comment by justinyoo** [comment]
It seems that the current build runner has an issue on targeting `net461` and `netcoreapp2.1`. Please push another commit to get the temporarily fixed build pipeline.

**Comment by disambiguationuk** [comment]
Any chance we could update the build task? Would really love to have this feature!

**Comment by gsteencg** [comment]
> Any chance we could update the build task? Would really love to have this feature!
- looks like setup-build is using a deprecated addPath call - https://github.com/microsoft/setup-msbuild/blob/master/src/main.ts

added an env var to allow the call until that task is changed/updated

**Comment by disambiguationuk** [comment]
Hey @justinyoo can we get an approval on this pull request if this is all good?

**Comment by disambiguationuk** [comment]
Bumping this, @justinyoo could you take a look at this?

**Comment by justinyoo** [comment]
Please refer to https://github.com/Azure/azure-functions-openapi-extension/pull/19

**Pull request closed without merging**
