### PR TITLE
Allow for empty route prefix

### PR DESCRIPTION
**Pull request by mkowalskigps**

### CODE REVIEW

**Comment by justinyoo** [comment]
@mkowalskigps Thanks for your PR!

I've missed some test cases around these methods. Once I add test cases based on current state, can you also update those tests to reflect your change as well, please?

**Comment by mkowalskigps** [comment]
Sure thing 👍

**Comment by justinyoo** [comment]
@mkowalskigps I've just added a few test cases for you to update for this PR. Would you be able to check at your side and update them, please? Apology for the delay.

**Comment by justinyoo** [comment]
@mkowalskigps Thanks for your contribution! It's now included to 1.5.1.

**Pull request merged**
