### PR TITLE
Support of Generic Lists to be a Response Type. 

### LINKED ISSUE #34: Type List for OpenApiPayloadAttribute not mapped correctly
Hi,

I have a Function like this, returning a `List<Product>`:
```
[FunctionName("ListProducts")]
[OpenApiOperation("products", "Serverless Microservices")]
**[OpenApiResponseBody(HttpStatusCode.OK, "application/json", typeof(List<Product>))]**
public async Task<IActionResult> ListProducts...
```

The Product type looks like this:
```
public class Product
{
        public Guid Id { get; set; }
        public string Name { get; set; }
}
```

The JSON rendered for this response type is this:
```
{
  **"List`1"**: {
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "Id": {
          "format": "uuid",
          "type": "string"
        },
        "Name": {
          "type": "string"
        }
      }
    }
  }
}
```
... which is not really what I expected ;-)
Shouldn't there be a `Product` type and then a list/array of `Product` in the JSON?

Thanks!

### PR DESCRIPTION
**Pull request by glennular**
Lists will set the Schema's Type to "Array" and the Items to the List-Type.

- Refactored the existing code in `OpenApiSchemaExtensions `to support all ILists
     * Based on https://stackoverflow.com/questions/951536/how-do-i-tell-whether-a-type-implements-ilist
     * Unit tests create to show issues, and resolution.
     * Resolves #34 

- Expanded `OpenApiPayloadAttributeExtensions` to be able to return Lists on the Response Bodies.
```
     "responses": {
          "200": {
            "description": "Payload of IList`1 of SampleResponseModel",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/SampleResponseModel"
              }
            },
            "x-ms-summary": "Sample response"
          }
```

### CODE REVIEW

**Comment by justinyoo** [comment]
@glennular Hi, After I merged #30 , it has merge conflict. Would you please resolve this so that I can merge yours?

**Comment by glennular** [comment]
@justinyoo I have merged in the latest dev branch, and was working on a fix around the JObject.  The JObject brought up a case of a Type that extends from List<>. So I have updated the code to include that case.

However I am blocked by #39. That issue includes issues around typing, so I'd like that to be resolved before I push the fix for this.

**Comment by justinyoo** [comment]
@glennular But the `JObject` type also extends `IDictionary<string, JToken>` and this can be anything. My implementation (not the root level) around this `JObject` was:

https://github.com/aliencube/AzureFunctions.Extensions/blob/556dfb1f4e4b1857dbf15fc8c52b41adda88737e/src/Aliencube.AzureFunctions.Extensions.OpenApi/Extensions/OpenApiSchemaExtensions.cs#L36-L41

**Comment by glennular** [comment]
I see #39 was resolved. I will finish the edge cases and push the final changes today or tomorrow.

**Comment by justinyoo** [comment]
I might have better/clear idea how I can deal with `JObject` and `Dictionary<>` once this is merged, although I closed #29

**Comment by glennular** [comment]
@justinyoo This is ready for your review. I switched the logic from any Type that inherits IList<> to having to specifically be a List<> or List<>. I think that would be the times you would want to use a OpenApi Array instead of the Object type. For example JObject extends IList<> but should be of type JObject not Array.

**Comment by justinyoo** [comment]
@glennular Thanks! Really appreciate it.

**Comment by justinyoo** [comment]
This has been released to [v1.5.2](https://www.nuget.org/packages/Aliencube.AzureFunctions.Extensions.OpenApi/1.5.2).

**Pull request merged**
